### ISSUE TITLE
Get rid of GOARCH=amd64 in Makefile

### ISSUE THREAD

**Issue by dberg1** [observatorium/observatorium#131]
As far as I can tell, observatorium builds fine on linux `ppc64le`.
Any reason to force `GOARCH` to `amd64` in the Makefile?

```
observatorium: deps main.go $(wildcard *.go) $(wildcard */*.go)
	CGO_ENABLED=0 GOOS=$(OS) GOARCH=amd64 GO111MODULE=on GOPROXY=https://proxy.golang.org go build -a -ldflags '-s -w' -o $@ .
```

**Comment by squat** [comment]
I think this was done lazily for people running on mac to be able to build the binary, add the binary to the container, and run the container in docker locally for testing.

Agreed that it would be nice to have a better/more flexible build!

cc @kakkoyun
