### ISSUE TITLE
Proposal add tracing API and OpenTelemetry collector

### ISSUE THREAD

**Issue by pavolloffay** [observatorium/observatorium#442]
This is a proposal to expose tracing ingestion API in the Observatorium backed by the OpenTelemetry collector. 

The OTEL collector does not provide any persistence, it is just a data forwarder as of now, however, it can be configured to send data to a variety of observability vendors or OSS projects like Jaeger or Zipkin or simply log data to the standard output. After this proposal is done we will be working on adding a storage/platform for trace data (e.g. Jaeger). 

This proposal contains two main action items:
1. Expose tracing ingestion API in the API service
2. Add deployments manifests for OpenTelemetry collector

### Expose tracing ingestion API
There are a couple of open-source tracing protocols out there - Zipkin, Jaeger and OpenTelemetry. At the moment the OpenTelemetry seems to be the most popular and it is projected to have the biggest adoption. Hence I would propose to use the OpenTelemetry as the trace ingestion API.

The OpenTelemetry protocol primarily supports gRPC for sending traces (I will refer to it as OTLP gRPC) with proto encoding. The HTTP protocol with protobuf encoding is as well supported. The JSON encoding is still in experimental mode. The majority of users use OTLP gRPC and the HTTP is used in environments where gRPC cannot be used (e.g. mobile clients). Because the Observatorium supports HTTP I would propose to start with OTLP HTTP and at the same time discuss how OTLP gRPC could be supported. 

#### Multitenancy 
The multitenancy should be handled the same way as it is for metrics and logs. The API service could add a HTTP header or attribute/label to data. This label would then be used in the collector to identify the tenant. 

### Add deployment manifests for OpenTelemetry collector

This is a pretty straightforward task. There is OpenTelemetry operator or HELM chart, but we could as well use plain Kubernetes manifests given the simplicity of this stateless component. 

#### Other related changes
The Observatorium API is instrumented with OpenTelemetry API. During the deployment it could be automatically configured to report data the OTEL collector as an internal user.

* OTLP HTTP: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp
* OTEL operator: https://github.com/open-telemetry/opentelemetry-operator
* OTEL Helm chart: https://github.com/open-telemetry/opentelemetry-helm-charts
* OTLP proto: https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto/trace/v1

**Comment by matej-g** [comment]
Hey @pavolloffay thanks for opening this! I'm excited to see tracing move forward. I'm curious about two things:
- I'm wondering about using gRPC vs HTTP - should we rather prefer starting with gRPC over HTTP? If gRPC is supposed to be the de facto standard, it looks like it would be worthwhile to primarily support gRPC and design the proposal with this in mind from the start. It might be more work but seems like it would be better pay off (and maybe my question is, is our aim to support both protocols from the beginning? Do we envision use of HTTP for the exceptional cases you mentioned in the issue?)
- Are there any specific authentication / authorization concerns regarding tracing API?

**Comment by pavolloffay** [comment]
> I'm wondering about using gRPC vs HTTP 

I would prefer to support both protocols for the given reasons (e.g. HTTP is used for mobile clients). 
If HTTP work will be more straightforward and quicker I would go for it and it parallel work on the gRPC spec. The idea is to get something working ASAP.


 > Are there any specific authentication / authorization concerns regarding tracing API?

I don't know at this point, most likely for the ingestion part no. @esnible is looking at auth in more detail - both ingestion and query.

**Comment by matej-g** [comment]
Thanks for clarifying the points @pavolloffay. Overall the proposal looks sounds. To move this further, my suggestion would be to create a (semi)official proposal PR with proposal document in MD format in `docs/proposals/drafts/`. You can base it on a previous draft / approved proposal, but there is no required format. I believe that would give everyone the best chance to get familiar with the proposal and comment on the specifics.

**Comment by pavolloffay** [comment]
@matej-g here is the proposal #443

**Comment by pavolloffay** [comment]
done
