### ISSUE TITLE
Interact with Observatorium using `obsctl`

### ISSUE THREAD

**Issue by saswatamcode** [observatorium/observatorium#455]
@onprem and I discussed this a bit today. 

It would be a nice idea to have a dedicated CLI for interacting with Observatorium.

The CLI, `obsctl`, will allow users to,
- Manage auth for multiple tenants by saving their configuration locally at a path like `$(HOME)/.obs/config`. So no need to manually configure OIDC flags while making requests each time 
- Configure rules for a tenant and view the configured rules
- View series, labels, and eventually query metrics for a tenant

In the future, this can also allow setting Alertmanager configs for tenants (refer to [tenant alerting proposal](https://github.com/observatorium/observatorium/pull/453)).

Open to feedback and suggestions! 🙂

**Comment by paulfantom** [comment]
Nice!
I wonder if you could use `${XDG_CONFIG_HOME}/obs` as a configuration directory? As per https://wiki.archlinux.org/title/XDG_Base_Directory spec.

**Comment by saswatamcode** [comment]
Discussed this with a few others. Seems like we can move forward with this idea with the CLI being in a separate repo, maybe observatorium/obsctl! 🙂

cc: @matej-g

**Comment by matej-g** [comment]
Sounds good @saswatamcode, if we have a consensus on the idea I'm happy to go for the new repo.

cc @observatorium/maintainers

**Comment by saswatamcode** [comment]
Repo has been created here: https://github.com/observatorium/obsctl!

**Comment by matej-g** [comment]
It's happening :partying_face: @saswatamcode beat me to it. Only remaining item for this issue for me would be to update README in this repo to include information on `obsctl`, once it's up and ready.

**Comment by jessicalins** [comment]
I wonder if we can close this issue since `obsctl` is already created and in use :tada: @saswatamcode what do you think?

**Comment by saswatamcode** [comment]
Sure @jessicalins! Let's close it!

**Comment by jessicalins** [comment]
done at https://github.com/observatorium/obsctl :tada: closing
