### ISSUE TITLE
probably invalid twitter link

### ISSUE THREAD

**Issue by frzifus** [observatorium/observatorium#476]
Probably the twitter link in the [governance](https://github.com/observatorium/observatorium/blob/3d467717ca3008a74ce645c2e7c4dd2e5e01f5a3/docs/community/governance.md#maintainers-team) file is not quite up to date?

> New maintainer is announced on the [Observatorium Twitter](https://twitter.com/0bservatorium) by an existing team member.

It points to https://twitter.com/0bservatorium.

![image](https://user-images.githubusercontent.com/10403402/163388452-3f8e5289-b976-445d-b265-0af145eff37d.png)

**Comment by jessicalins** [comment]
fixed by https://github.com/observatorium/observatorium/pull/477
