### ISSUE TITLE
The observatorium-api manifest should allow more granular TLS configuration.

### ISSUE THREAD

**Issue by nmagnezi** [observatorium/observatorium#57]
In a recent [PR to observatorium/configuration](https://github.com/observatorium/configuration/pull/273), I added the option to mount a secret with a cert file, private key file, and ca file.

The first two are required to enable TLS for Observatorium API gateway while providing the latter will essentially enable mTLS.

As a followup to a discussion with @brancz, we aimed to support both TLS as well as mTLS in plain manifests and Observatorium operator.

This can be achieve by separating the sensitive information to a secret and the ca file to ConfigMap (and mount them both). The ConfigMap should be optional.

In a case where users provide a secret that contains cert file, private key but not a ca file in ConfigMap. The [observatorium-api](https://github.com/observatorium/observatorium/blob/85e81bbf17de5a97d301d8093bc8066e4b17eaf4/jsonnet/lib/observatorium-api.libsonnet) manifest will [reject it](https://github.com/observatorium/observatorium/blob/85e81bbf17de5a97d301d8093bc8066e4b17eaf4/jsonnet/lib/observatorium-api.libsonnet#L229) due to manifest validations. Those should be fixed since it is essentially all `withTLS` parameters or none.

**Comment by brancz** [comment]
`withTLS` should be change in my opinion, to only accept cert and key, and a new patch should be introduced, maybe called `withClientTLS`, that would provision that flag separately.

**Comment by brancz** [comment]
Additionally those two patches that I proposed, don't only need to add flags, and mounts potentially it also needs to reconfigure liveness and readiness probes.

I would expect the following to be happening (and if not then that would be a bug):

* no TLS configuration: things are as they are today
* `withTLS` liveness and readiness probes use https, but ignore the CA
* `withClientTLS` same as `withTLS` as the two endpoints should not be authenticated, thus not need a client cert to be presented (I don't know off the top of my head if this is the case today)

**Comment by nmagnezi** [comment]
Resolved by [PR-61](https://github.com/observatorium/observatorium/pull/61)
