### ISSUE TITLE
[RFE] Ephemeral storage support for development environments

### ISSUE THREAD

**Issue by leifmadsen** [observatorium/observatorium#73]
I have access to an on-demand OpenShift environment for testing (QuickLAB) but it does not support persistent storage. Ability to have ephemeral storage support (emptyDir or whatever) would be useful for development purposes. I would not expect to see this recommended or used in a production environment.

(Not sure what, if any, code changes would be required to support this, or if this is just a documentation problem.)

Thanks!

**Comment by squat** [comment]
Hi @leifmadsen if you take a look at the manifests in examples/manifests, you'll find there are no resources with persistent storage. Which manifests are you referring to?

**Comment by squat** [comment]
Closing as stale. Please comment or re-open if you still have any questions :))

**Comment by leifmadsen** [comment]
Sorry I missed this. I believe I'm talking about the minIO integration which requires a backing store, correct?

**Comment by squat** [comment]
Hi @leifmadsen there are no minio manifests or any reference to it anywhere in this repo. This repo is purely about the API exposed by observatorium. Maybe you are interested in the github.com/observatorium/deployments repo?

In any case, it is certainly possible to run minio without a PVC, it just means that whenever the pod is deleted, the data will all be lost
