### ISSUE TITLE
Feature request: mtls to support wildcards on the subjects

### ISSUE THREAD

**Issue by clyang82** [observatorium/observatorium#82]
From the rbac example - https://github.com/observatorium/observatorium/blob/master/examples/rbac/simple.yaml
The `subjects` must be list here one by one. 
Our case is all the users in one tenant can be able to write or read the metrics, so that can we support the wildcards on the `subjects`? Thanks.

FYI @brancz

**Comment by brancz** [comment]
yeah I think wildcards make sense here

**Comment by squat** [comment]
I think that for the time being we are satisfied with using RBAC groups for handling use-cases you have, right?

Note: when using mTLS for authentication, Observatorium loads all of the values of the Organizational Unit (OU) as groups for the client.

example of defining a role binding to a group: https://github.com/observatorium/observatorium/blob/master/test/config/rbac.yaml#L27-L32

**Comment by clyang82** [comment]
from the latest discussion
- For the read-only RoleBinding, the subject of the cert will be a fixed value.   
- For read-write, the subject is an organization
so that we do not need to support wildcards on subjects. 
@bjoydeep  please correct me If I am wrong. Thanks.

**Comment by squat** [comment]
Closing this for now as it seems it is not strictly needed
